services:
  nginx:
    image: phoenyxxed/nginx:5b74726
    container_name: nginx-container
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend-1
      - backend-2
  frontend:
    image: phoenyxxed/frontend:5b74726
    container_name: frontend-container
  backend-1:
    image: phoenyxxed/backend:5b74726
    container_name: backend-container-1
  backend-2:
    image: phoenyxxed/backend:5b74726
    container_name: backend-container-2
